pipeline {

    agent {
        label 'django-agent'
    }

    options {
        skipDefaultCheckout(true)
    }

    environment {

        DJANGO_HOST = "172.31.46.255"
        DJANGO_USER = "ubuntu"

        REMOTE_PATH = "/home/ubuntu/chatapp-deploy/chatapp-ubuntu-22.04"

        LOCAL_PATH = "${WORKSPACE}/chatapp-ubuntu-22.04"
    }

    stages {

        stage('Checkout Code') {

            steps {

                git branch: 'main',
                    url: 'https://github.com/jatinthakur011/chat-app.git'

            }

        }

        stage('SonarQube Analysis') {

            steps {

                dir('chatapp-ubuntu-22.04') {

                    script {

                        def scannerHome = tool 'SonarScanner'

                        withSonarQubeEnv('SonarQube') {

                            sh "${scannerHome}/bin/sonar-scanner"

                        }

                    }

                }

            }

        }

        stage('Quality Gate') {

            steps {

                timeout(time: 5, unit: 'MINUTES') {

                    waitForQualityGate abortPipeline: true

                }

            }

        }

        stage('Deploy Files') {

            steps {

                sshagent(['agent-key']) {

                    sh '''
                    rsync -av --delete \
                    --exclude='.git' \
                    --exclude='venv' \
                    --exclude='db.sqlite3' \
                    --exclude='__pycache__' \
                    --exclude='*.pyc' \
                    -e "ssh -o StrictHostKeyChecking=no" \
                    ${LOCAL_PATH}/ \
                    ${DJANGO_USER}@${DJANGO_HOST}:${REMOTE_PATH}/
                    '''

                }

            }

        }

        stage('Run Migration') {

            steps {

                sshagent(['agent-key']) {

                    sh '''
                    ssh -o StrictHostKeyChecking=no \
                    ${DJANGO_USER}@${DJANGO_HOST} "

                    cd ${REMOTE_PATH}/fundoo

                    source venv/bin/activate

                    python manage.py migrate --noinput

                    "
                    '''

                }

            }

        }

        stage('Restart Django') {

            steps {

                sshagent(['agent-key']) {

                    sh '''
                    ssh -o StrictHostKeyChecking=no \
                    ${DJANGO_USER}@${DJANGO_HOST} "

                    sudo systemctl restart django

                    "
                    '''

                }

            }

        }

        stage('Verify Service') {

            steps {

                sshagent(['agent-key']) {

                    sh '''
                    ssh -o StrictHostKeyChecking=no \
                    ${DJANGO_USER}@${DJANGO_HOST} "

                    echo ===== SERVER =====
                    hostname

                    echo ===== DJANGO STATUS =====
                    sudo systemctl is-active django

                    "
                    '''

                }

            }

        }

    }

}