pipeline {
    agent any

    stages {

        stage('Test Django SSH') {

            steps {

                sshagent(['controller-key']) {

                    sh '''
                    ssh -o StrictHostKeyChecking=no ubuntu@172.31.46.255 "
                        echo ===== SERVER =====
                        hostname

                        echo ===== USER =====
                        whoami

                        echo ===== DIRECTORY =====
                        pwd
                    "
                    '''
                }

            }

        }

    }

}