apiVersion: v1
kind: Secret

metadata:
  name: mysql-secret
  namespace: chatapp

type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: jatuthakur1234
  MYSQL_DATABASE: chatdb

  DB_NAME: chatdb
  DB_USER: root
  DB_PASSWORD: jatuthakur1234
